sudo: required
services:
  - docker

before_install:
  - docker build -t andresj/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run andresj/react-test npm test -- --coverage

after_success:
  - docker build -t andresj/multi-client ./client
  - docker build -t andresj/multi-server ./server
  - docker build -t andresj/multi-worker ./worker
  - docker build -t andresj/multi-nginx ./nginx
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push andresj/multi-client
  - docker push andresj/multi-server
  - docker push andresj/multi-worker
  - docker push andresj/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-823870540165
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: $AWS_SECRET_KEY
